window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isiOS=!1;if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){window.isiOS=!0}
window.isiOSVersion='';if(window.isiOS){var version=(navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);if(version!==null){window.isiOSVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isIE=!!document.documentMode;window.browserLang=(window.navigator.userLanguage||window.navigator.language).toUpperCase().slice(0,2);window.tildaBrowserLang=window.browserLang;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t393_appearMenu(recId){if(window.innerWidth>980){var recs=document.querySelectorAll('.t393');var scrollTop=window.pageYOffset;var body=document.body;var html=document.documentElement;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,html.clientHeight,html.scrollHeight,html.offsetHeight);for(var i=0;i<recs.length;i++){var rec=recs[i];var appearOffset=rec.getAttribute('data-appearoffset');var hideOffset=rec.getAttribute('data-hideoffset');if(appearOffset){if(appearOffset.indexOf('vh')>-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);if(scrollTop>=appearOffset){if(rec.style.visibility==='hidden'){rec.style.visibility='visible';t393__fadeIn(rec)}}else{rec.style.visibility='hidden'}}
if(hideOffset){if(hideOffset.indexOf('vh')>-1){hideOffset=Math.floor((window.innerHeight*(parseInt(hideOffset)/100)))}
hideOffset=parseInt(hideOffset,10);if(scrollTop+window.innerHeight>=documentHeight-hideOffset){if(rec.style.visibility!=='hidden'){rec.style.visibility='hidden'}}else if(appearOffset){if(scrollTop>=appearOffset){rec.style.visibility='visible'}}else{rec.style.visibility='visible'}}}}}
function t393__fadeIn(el){if(el.style.display==='block')return;var opacity=0;el.style.opacity=opacity;el.style.display='block';var timer=setInterval(function(){el.style.opacity=opacity;opacity+=0.1;if(opacity>=1.0){clearInterval(timer);el.style.display=''}},30)}
function t898_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t898');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var whatsApp=rec.querySelector('.t898__icon-whatsapp_wrapper');if(whatsApp){var whatsAppHref=whatsApp.getAttribute('href');if(whatsAppHref&&(whatsAppHref.indexOf('whatsapp://')>-1||whatsAppHref.indexOf('wa.me')>-1)){t898_removeExtraSymbolsFromWhatsApp(whatsApp,whatsAppHref)}}
if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t898_removeExtraSymbolsFromWhatsApp(whatsApp,whatsAppHref){if(whatsAppHref&&whatsAppHref.indexOf('?text=')!==-1){var whatsAppHrefArr=whatsAppHref.split('?text=');whatsAppHrefArr[0]=whatsAppHrefArr[0].replace(/[\(\)+-]/g,'');whatsAppHref=whatsAppHrefArr[0]+'?text='+whatsAppHrefArr[1]}else{whatsAppHref=whatsAppHref.replace(/[\(\)+-]/,'')}
whatsApp.setAttribute('href',whatsAppHref)}
function t712_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t712_fixcontentheight(id){var rec=document.getElementById('rec'+id);if(!rec)return;var cover=rec.querySelector('.t-cover');var filter=rec.querySelector('.t-cover__filter');var carrier=rec.querySelector('.t-cover__carrier');var wrapper=rec.querySelector('.t-cover__wrapper');var container=rec.querySelector('.t-cover__container');var coverHeight=cover?cover.offsetHeight:0;var content=rec.querySelector('div[data-hook-content]');var contentHeight=content?content.offsetHeight:0;if(contentHeight>300&&coverHeight<contentHeight){var youTubeRecommendationsSpace=120;if(contentHeight>1000)youTubeRecommendationsSpace+=100;contentHeight+=youTubeRecommendationsSpace;console.log('auto correct cover height: '+contentHeight);if(cover)cover.style.height=contentHeight+'px';if(filter)filter.style.height=contentHeight+'px';if(carrier)carrier.style.height=contentHeight+'px';if(wrapper)wrapper.style.height=contentHeight+'px';if(container)container.style.height=contentHeight+'px';if(!window.isMobile){setTimeout(function(){var videoBlock=rec.querySelector('.t-cover__carrier');if(videoBlock&&videoBlock.querySelector('iframe')){console.log('correct video from cover_fixcontentheight');window.setWidthAndHeightVideo(videoBlock,contentHeight+'px','youtube')}},2000)}}}
var t776_POPUP_SHOWED_EVENT_NAME='catalog:popupShowed';var t776_POPUP_CLOSED_EVENT_NAME='catalog:popupClosed';function t776__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t776_initPopup(recid);t776__hoverZoom_init(recid);t776__updateLazyLoad(recid);t776__alignButtons_init(recid);t_onFuncLoad('t_store_addProductQuantityEvents',function(){t776_initProductQuantity(recid)});var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);document.body.dispatchEvent(event)},500)}
function t776_initProductQuantity(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var productList=rec.querySelectorAll('.t776__col, .t776__product-full');Array.prototype.forEach.call(productList,function(product){t_store_addProductQuantityEvents(product)})}
function t776__showMore(recid){var rec=document.querySelector('#rec'+recid+' .t776');if(!rec)return;var cardsCount=parseInt(rec.getAttribute('data-show-count'),10);if(isNaN(cardsCount)||cardsCount<1)return;var showMoreButton=rec.querySelector('.t776__showmore');if(!showMoreButton)return;if(!showMoreButton.querySelector('td').textContent){showMoreButton.querySelector('td').textContent=t776__dict()}
var firstProductCard=rec.querySelector('.t776__col');if(!firstProductCard)return;var productCards=rec.querySelectorAll('.t776__col');var cardsLenght=productCards.length;if(!window.getComputedStyle)return;var originalDisplayProperty=window.getComputedStyle(firstProductCard).display;if(cardsLenght>cardsCount){showMoreButton.style.display='inline-block'}
Array.prototype.forEach.call(productCards,function(card){card.style.display='none'});t776__showSeparator(rec,cardsCount);for(var i=0;i<cardsCount;i++){if(productCards[i]){productCards[i].style.display=originalDisplayProperty}}
window.addEventListener('resize',function(){Array.prototype.forEach.call(productCards,function(card){card.style.display='none'});for(var i=0;i<cardsCount;i++){if(productCards[i]){productCards[i].style.display=originalDisplayProperty}}});var showedCardsCount=0;showMoreButton.addEventListener('click',function(){Array.prototype.forEach.call(productCards,function(product){if(product.style.display===originalDisplayProperty){showedCardsCount++}});cardsCount+=showedCardsCount;for(var i=0;i<cardsCount;i++){if(productCards[i]){productCards[i].style.display=originalDisplayProperty}}
if(cardsCount>=cardsLenght){showMoreButton.style.display='none'}
t776__showSeparator(rec,cardsCount);if(rec.querySelector('[data-buttons-v-align]')){t776__alignButtons(recid)}
if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t776__showSeparator(rec,cardsCount){if(window.jQuery&&rec instanceof jQuery){rec=rec.get(0)}
var allSeparators=rec.querySelectorAll('.t776__separator_number');Array.prototype.forEach.call(allSeparators,function(separator){separator.classList.add('t776__separator_hide');if(separator.getAttribute('data-product-separator-number')<=cardsCount){separator.classList.remove('t776__separator_hide')}})}
function t776__dict(){var dictionary={EN:'Load more',RU:'Загрузить еще',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var language=window.browserLang;return dictionary[language]?dictionary[language]:dictionary.EN}
function t776__alignButtons_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;if(!rec.querySelector('[data-buttons-v-align]')){return}
try{t776__alignButtons(recid);if(document.querySelector('.t-records').getAttribute('data-tilda-mode')==='edit'){setInterval(function(){t776__alignButtons(recid)},200)}
window.addEventListener('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&window.isMobile){return}
t776__alignButtons(recid)}));var wrapperBlock=rec.querySelector('.t776');if(wrapperBlock){wrapperBlock.addEventListener('displayChanged',function(){t776__alignButtons(recid)})}
if(window.isMobile){window.addEventListener('orientationchange',function(){t776__alignButtons(recid)})}}catch(error){console.log('buttons-v-align error: '+error.message)}}
function t776__alignButtons(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var maxHeight=0;var wrappers=rec.querySelectorAll('.t776__textwrapper');var container=rec.querySelector('.t776__parent');if(container){var productInRow=parseInt(container.getAttribute('data-blocks-per-row'),10)}
var mobileView=window.innerWidth<=480;var tableView=window.innerWidth<=960&&window.innerWidth>480;var mobileOneRow=window.innerWidth<=960&&rec.querySelector('.t776__container_mobile-flex');var mobileTwoItemsInRow=window.innerWidth<=480&&rec.querySelector('.t776 .mobile-two-columns');if(mobileView){productInRow=1}
if(tableView){productInRow=2}
if(mobileTwoItemsInRow){productInRow=2}
if(mobileOneRow){productInRow=999999}
var count=1;var wrappersInRow=[];Array.prototype.forEach.call(wrappers,function(wrapper){wrapper.style.height='auto';if(productInRow===1){wrapper.style.height='auto'}else{wrappersInRow.push(wrapper);if(wrapper.offsetHeight>maxHeight){maxHeight=wrapper.offsetHeight}
Array.prototype.forEach.call(wrappersInRow,function(wrapperInRow){wrapperInRow.style.height=maxHeight+'px'});if(count===productInRow){count=0;maxHeight=0;wrappersInRow=[]}
count++}})}
function t776__hoverZoom_init(recid){if(window.isMobile){return}
var rec=document.getElementById('rec'+recid);if(!rec)return;var parent=rec.querySelector('.t776__parent');try{if(parent&&parent.getAttribute('data-hover-zoom')!=='yes'){return}
var hoverScript='https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js';if(document.querySelector("script[src^='"+hoverScript+"']")){t_onFuncLoad('t_hoverZoom_init',function(){t_hoverZoom_init(recid)})}else{var script=document.createElement('script');script.type='text/javascript';script.src=hoverScript;script.onload=function(){setTimeout(function(){t_hoverZoom_init(recid)},500)};script.onerror=function(error){console.log('Upload script error: ',error)};document.head.appendChild(script)}}catch(error){console.log('Zoom image init error: '+error.message)}}
function t776__updateLazyLoad(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var scrollContainer=rec.querySelector(' .t776__container_mobile-flex');var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t776_initPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var openerLink=rec.querySelectorAll('[href^="#prodpopup"]');var popup=rec.querySelector('.t-popup');Array.prototype.forEach.call(openerLink,function(link){var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');var productLinks=document.querySelectorAll('.r a[href$="#!/tproduct/'+recid+'-'+productLid+'"]');Array.prototype.forEach.call(productLinks,function(productLink){productLink.addEventListener('click',function(){if(rec.querySelector('[data-product-lid="'+productLid+'"]')){var linkToPopup=product.querySelector('[href^="#prodpopup"]');if(linkToPopup){var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);linkToPopup.dispatchEvent(event)}}})});link.addEventListener('click',clickOnceHandler,!1);function clickOnceHandler(event){event.preventDefault();var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t776__product-'+productLid+'')});link.removeEventListener('click',clickOnceHandler,!1)}
link.addEventListener('click',showPopupHandler,!1);function showPopupHandler(event){event.preventDefault();if(event.target.classList.contains('t1002__addBtn')||event.target.parentNode.classList.contains('t1002__addBtn')){return}
t776_showPopup(recid);var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');var allProducts=popup.querySelectorAll('.js-product');Array.prototype.forEach.call(allProducts,function(product){product.style.display='none'});var productFull=popup.querySelector('.js-product[data-product-lid="'+productLid+'"]');if(productFull){productFull.style.display='block'}
var analitics=popup.getAttribute('data-track-popup');if(analitics&&productFull&&window.Tilda){var productName=productFull.querySelector('.js-product-name');if(productName){var virtualTitle=productName.textContent;if(!virtualTitle){virtualTitle='prod'+productLid}
Tilda.sendEventToStatistics(analitics,virtualTitle)}}
var currentUrl=window.location.href;if(currentUrl.indexOf('#!/tproduct/')===-1&&currentUrl.indexOf('%23!/tproduct/')===-1){if(typeof history.replaceState!=='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+productLid)}}
t776_updateSlider(recid+' #t776__product-'+productLid);if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}});if(document.querySelectorAll('#record'+recid).length===0){t776_checkUrl(recid)}
if(popup&&popup.hasAttribute('data-fixed-button')){t776_fixedPopupButton(recid)}}
function t776_checkUrl(recid){var currentUrl=window.location.href;var tprodIndex=(currentUrl.indexOf('#!/tproduct/')+1||currentUrl.indexOf('%23!/tproduct/')+1||currentUrl.indexOf('#%21%2Ftproduct%2F')+1||currentUrl.indexOf('#!%2Ftproduct%2F')+1||currentUrl.indexOf('%23%21%2Ftproduct%2F')+1)-1;if(tprodIndex!==-1){var currentUrl=currentUrl.substring(tprodIndex,currentUrl.length);var curProdLid=currentUrl.substring(currentUrl.indexOf('-')+1,currentUrl.length);if(curProdLid){var curProdLidMatch=curProdLid.match(/([0-9]+)/g);if(curProdLidMatch){curProdLid=curProdLidMatch[0]}}
if(currentUrl.indexOf(recid)===-1)return;var rec=document.getElementById('rec'+recid);if(!rec)return;if(currentUrl.indexOf(recid)!==0&&rec.querySelector('[data-product-lid="'+curProdLid+'"]')){var currentLink=rec.querySelector('[data-product-lid="'+curProdLid+'"] [href^="#prodpopup"]');var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);if(currentLink){currentLink.dispatchEvent(event)}}}}
function t776_updateSlider(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var slider=rec.querySelector('.t-slds__container');var paddingLeft=parseInt(slider.style.paddingLeft)||0;var paddingRight=parseInt(slider.style.paddingRight)||0;var sliderWrapper=rec.querySelector('.t-slds__items-wrapper');var sliderWidth=slider.clientWidth-(paddingLeft+paddingRight);var position=parseFloat(sliderWrapper.getAttribute('data-slider-pos'));sliderWrapper.style.transform='translate3d(-'+sliderWidth*position+'px, 0, 0)';t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t776_showPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var popup=rec.querySelector('.t-popup');popup.style.display='block';setTimeout(function(){popup.querySelector('.t-popup__container').classList.add('t-popup__container-animated');popup.classList.add('t-popup_show');t_triggerEvent(popup,t776_POPUP_SHOWED_EVENT_NAME)},50);setTimeout(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},300);var body=document.body;if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');body.classList.add('t-body_popupshowed');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event);popup.addEventListener('mousedown',function(event){var windowWidth=window.innerWidth;var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(event.clientX>windowWithoutScrollBar){return}
if(event.target===this){t776_closePopup(body,popup)}});var closeButtons=rec.querySelectorAll('.t-popup__close, .t776__close-text');Array.prototype.forEach.call(closeButtons,function(button){button.addEventListener('click',function(){t776_closePopup(body,popup)})});document.addEventListener('keydown',function(event){var isGalleryShowedOldLib=document.body.classList.contains('t-zoomer__show');if(isGalleryShowedOldLib)return;var isGalleryShowedNewLib=document.body.classList.contains('t-zoomer__active');if(isGalleryShowedNewLib)return;var isPopupShowed=document.body.classList.contains('t-body_popupshowed');if(!isPopupShowed)return;if(popup&&popup.classList.contains('t-popup_show')){if(event.keyCode===27){t776_closePopup(body,popup)}}});if(window.isSafari){setTimeout(function(){popup.scrollTop=1})}}
function t776_closePopup(body,popup){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');body.classList.remove('t-body_popupshowed');popup.classList.remove('t-popup_show');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event);var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=currentUrl.indexOf('%23!/tproduct/')}
currentUrl=currentUrl.substring(0,indexToRemove);setTimeout(function(){popup.scrollTop=0;popup.style.display='none';if(typeof history.replaceState!=='undefined'){window.history.replaceState('','',currentUrl)}},300);t_triggerEvent(popup,t776_POPUP_CLOSED_EVENT_NAME)}
function t776_fixedPopupButton(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var MOBILE_MAX_WIDTH=560;var popup=rec.querySelector('.t-popup');var popupContainer=popup.querySelector('.t-popup__container');var btnWrappers=rec.querySelectorAll('.t776__btn-wrapper');Array.prototype.forEach.call(btnWrappers,function(el){el.classList.add('t776__btn-wrapper-fixed')});function addStyle(){popupContainer.style.paddingBottom='90px';popupContainer.style.cssText+=';transform:none !important;'}
function resetStyle(){popupContainer.style.paddingBottom='';popupContainer.style.transform=''}
function handleResize(){if(window.innerWidth>MOBILE_MAX_WIDTH){resetStyle();return}
addStyle()}
if(window.isMobile){window.addEventListener('orientationchange',handleResize)}
popup.addEventListener(t776_POPUP_SHOWED_EVENT_NAME,function(){setTimeout(function(){handleResize()})});popup.addEventListener(t776_POPUP_CLOSED_EVENT_NAME,function(){resetStyle()});window.addEventListener('resize',handleResize)}
function t796_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t796');if(!container)return;var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return!1;if(screenMax&&windowWidth>parseInt(screenMax,10))return!1;var shapeBorder=rec.querySelector('.t796__shape-border');var shapeRecId=container.getAttribute('data-shape-rec-ids');if(shapeRecId){shapeRecId=shapeRecId.split(',');for(var i=0;i<shapeRecId.length;i++){var shapeId=shapeRecId[i];var currentRec=document.querySelector('#rec'+shapeId);var currentShape=shapeBorder.cloneNode(!0);t796_setColor(rec,currentShape);t796_addDivider(currentRec,currentShape)}}else{var excludesBlocks=[215,316,390,651,702,706,708,750,756,766,825,862,868,943,945,674];var excludes='';for(var i=0;i<excludesBlocks.length;i++){excludes+=':not([data-record-type="'+excludesBlocks[i]+'"])'}
if(excludes.slice(-1)===','){excludes=excludes.slice(0,-1)}
var recs=[];if(shapeBorder.classList.contains('t796__shape-border_top')||shapeBorder.classList.contains('t796__shape-border_top-flip')){recs=t796__nextAll(rec,excludes)}
if(shapeBorder.classList.contains('t796__shape-border_bottom')||shapeBorder.classList.contains('t796__shape-border_bottom-flip')){recs=t796__prevAll(rec,excludes)}
if(recs.length!==0){var currentShape=shapeBorder.cloneNode(!0);t796_setColor(rec,currentShape);t796_addDivider(recs[0],currentShape)}}}
function t796_setColor(rec,shape){if(shape.getAttribute('data-fill-color'))return;var nearestBlock;if(shape.classList.contains('t796__shape-border_bottom')||shape.classList.contains('t796__shape-border_bottom-flip')){var nextBlock=rec.nextElementSibling;if(nextBlock){nearestBlock=nextBlock.matches('.r')?nextBlock:!1}}else{var prevBlock=rec.previousElementSibling;if(prevBlock){nearestBlock=prevBlock.matches('.r')?prevBlock:!1}}
if(!nearestBlock)return;var fillColor=nearestBlock.getAttribute('data-bg-color');if(!fillColor)return;var svg=shape.querySelector('.t796__svg');if(svg)svg.style.fill=fillColor}
function t796_addDivider(rec,shape){if(!rec)return;rec.setAttribute('data-animationappear','off');rec.classList.remove('r_hidden');var covers=rec.querySelectorAll('.t-cover');var zeroBlock=rec.querySelector('.t396');if(covers.length>0||zeroBlock){if(covers.length>0){Array.prototype.forEach.call(covers,function(cover){shape=covers.length>1?shape.cloneNode(!0):shape;var showLayers=cover.querySelectorAll('.t557__snow-layer');if(showLayers.length>0)shape.style.zIndex=1;var coverFilter=cover.querySelector('.t-cover__filter');if(coverFilter)coverFilter.insertAdjacentElement('afterend',shape);shape.style.display='block'})}
if(zeroBlock){zeroBlock.insertAdjacentElement('afterend',shape);rec.style.position='relative';var zeroFilter=zeroBlock.querySelector('.t396__filter');if(zeroFilter){var zIndex=1;var zeroArtboard=zeroBlock.querySelector('.t396__artboard');var isVisible=getComputedStyle(zeroArtboard,null).overflow==='visible';if(!isVisible)zIndex=99;shape.style.zIndex=zIndex}
shape.style.display='block'}}else{var wrapper=rec;var recordType=parseInt(rec.getAttribute('data-record-type'));if(!wrapper)return!0;wrapper.appendChild(shape);wrapper.style.position='relative';var excludesBlocks=[125,331,554,746,754,776,778,786,858,896,897,924,915,943,945,951,1004,1025];if(excludesBlocks.indexOf(recordType)===-1){var notZIndexBlocks=[983];var firstDiv=wrapper.querySelector('div');firstDiv.style.position='relative';firstDiv.classList.add('t796_cont-near-shape-divider');if(notZIndexBlocks.indexOf(recordType)!==-1){firstDiv.style.zIndex=0}else{firstDiv.style.zIndex='1'}}
var blocks=[195,246,279,675,694,734,823,938];if(blocks.indexOf(recordType)!==-1){shape.style.zIndex=1}
shape.style.display='block'}}
function t796__nextAll(element,selector){var nextElements=[];var nextElement=element;while(nextElement.nextElementSibling){nextElement=nextElement.nextElementSibling;if(nextElement.id==='t-footer'){var footerElements=nextElement.querySelectorAll('.r');if(footerElements.length!==0){nextElement=footerElements[0];if(nextElement.matches(selector)){nextElements.push(nextElement)}
nextElements=nextElements.concat(t796__nextAll(nextElement,selector))}}else if(nextElement.matches(selector)){nextElements.push(nextElement)}}
return nextElements}
function t796__prevAll(element,selector){var prevElements=[];var prevElement=element;while(prevElement.previousElementSibling){prevElement=prevElement.previousElementSibling;if(prevElement.id==='t-header'){var headerElements=prevElement.querySelectorAll('.r');if(headerElements.length!==0){prevElement=headerElements[headerElements.length-1];if(prevElement.matches(selector)){prevElements.push(prevElement)}
prevElements=prevElements.concat(t796__prevAll(prevElement,selector))}}else if(prevElement.matches(selector)){prevElements.push(prevElement)}}
return prevElements}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
function t509_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t509');if(!container)return;var images=rec.querySelectorAll('.t509__blockimg');t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)});for(var i=0;i<images.length;i++){var image=images[i];var imageWidth=image.getAttribute('data-image-width');var imageHeight=image.getAttribute('data-image-height');if(imageHeight.indexOf('vh')===-1){imageHeight=parseInt(imageHeight,10)}else{imageHeight=parseInt(imageHeight,10)/100*window.innerHeight}
var imageRatio=imageHeight/imageWidth;var imagePadding=imageRatio*100;image.style.paddingBottom=imagePadding+'%'}
if(window.innerWidth>960){var desktopImage=rec.querySelector('.t509__desktopimg');if(desktopImage){var height=desktopImage.clientHeight;var textWrappers=rec.querySelectorAll('.t509__textwrapper');for(var i=0;i<textWrappers.length;i++){textWrappers[i].style.height=height+'px'}}}}
function t230_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var wrapperBlock=rec.querySelector('.t230');var videoLazy=rec.querySelector('.t-video-lazyload');if(videoLazy){t_onFuncLoad('t_video_lazyload__setHeight',function(){t_video_lazyload__setHeight(videoLazy);window.addEventListener('resize',function(){t_video_lazyload__setHeight(videoLazy)});if(!wrapperBlock)return;wrapperBlock.addEventListener('displayChanged',function(){t_video_lazyload__setHeight(videoLazy)})})}}
function t690_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t498_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var containers=rec.querySelectorAll('.t498 .t-container');for(var i=0;i<containers.length;i++){var container=containers[i];var heightBox=0;var cols=container.querySelectorAll('.t498__col');for(var j=0;j<cols.length;j++){cols[j].style.height=''}
for(var j=0;j<cols.length;j++){var col=cols[j];var colStyle=getComputedStyle(col,null);var colPaddingTop=parseInt(colStyle.paddingTop)||0;var colPaddingBottom=parseInt(colStyle.paddingBottom)||0;var colHeight=col.clientHeight-(colPaddingTop+colPaddingBottom);var colWrap=col.querySelector('.t498__col-wrapper');var colWrapStyle=getComputedStyle(colWrap,null);var colWrapPaddingTop=parseInt(colWrapStyle.paddingTop)||0;var colWrapPaddingBottom=parseInt(colWrapStyle.paddingBottom)||0;var colWrapHeight=colWrap.clientHeight-(colWrapPaddingTop+colWrapPaddingBottom);if(colHeight<colWrapHeight){col.style.height=colWrapHeight+'px';heightBox=colWrapHeight}
if(colHeight>heightBox)heightBox=colHeight}
if(window.innerWidth>=960){for(var j=0;j<cols.length;j++){cols[j].style.height=heightBox+'px'}}else{for(var j=0;j<cols.length;j++){cols[j].style.height='auto'}}}};function t214__updateLazyLoad(recid){var scrollContainer=document.querySelector('#rec'+recid+' .t214__container_mobile-flex');var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t601_init(recid){var el=$('#rec'+recid);var slide1=el.find('[data-slide-index=1]');var imagesSlide1=slide1.find('.t601__img');imagesSlide1.on('load',function(){if($(this).parents('.t-slides__item[data-slide-index=1]').length==0){return}
t_slides_setSliderHeight(recid)})}
function t554__init(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var wrapperBlock=rec.querySelector('.t554');var mapElement=rec.querySelector('.t554_map');var card=rec.querySelector('.t554__card');var generalWrapper=rec.querySelector('.t554__general-wrapper');if(!wrapperBlock||!mapElement||!card||!generalWrapper)return;t554__calcHeight(mapElement,card,generalWrapper);wrapperBlock.addEventListener('displayChanged',function(){t554__calcHeight(mapElement,card,generalWrapper)})}
function t554__calcHeight(mapElement,card,generalWrapper){generalWrapper.style.paddingBottom=null;var paddingTop=parseInt(mapElement.style.paddingTop,10)||0;var paddingBottom=parseInt(mapElement.style.paddingBottom,10)||0;var mapHeight=mapElement.clientHeight-(paddingTop+paddingBottom);var cardHeight=parseInt(card.offsetHeight,10);var cardTop=parseInt((card.style.top||'').replace('px',''),10);if(generalWrapper&&mapHeight<cardHeight+cardTop&&window.innerWidth>960&&generalWrapper.classList.contains('t554__general-wrapper_padding')){var mapPaddingBottom=cardHeight+cardTop-mapHeight;generalWrapper.style.paddingBottom=mapPaddingBottom+'px'}}
function t678_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t967_setLogoPadding(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menu=rec.querySelector('.t967');var logo=menu?menu.querySelector('.t967__logowrapper'):null;var leftWrap=menu?menu.querySelector('.t967__leftwrapper'):null;var rightWrap=menu?menu.querySelector('.t967__rightwrapper'):null;var logoWidth=logo?logo.offsetWidth:0;if(leftWrap)leftWrap.style.paddingRight=((logoWidth/2)+50)+'px';if(rightWrap)rightWrap.style.paddingRight=((logoWidth/2)+50)+'px'}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});document.addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href$="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});t702__lazyLoad();if(analitics&&window.Tilda){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,popupTooltipHook)})}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup(recId)});popupCloseBtn.addEventListener('click',function(){t702_closePopup(recId)});if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recId);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed')},300)}}})}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup(recId)}
popup.addEventListener('tildamodal:show'+popupTooltipHook,function(){document.addEventListener('keydown',t702_escClosePopup)});popup.addEventListener('tildamodal:close'+popupTooltipHook,function(){document.removeEventListener('keydown',t702_escClosePopup)});rec.addEventListener('conditional-form-init',function(){t_onFuncLoad('t_form__conditionals_addFieldsListeners',function(){t_form__conditionals_addFieldsListeners(recId,function(){t_popup__resizePopup(recId)})})},{once:!0})}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=typeof window.pageYOffset!=='undefined'?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return;if(screenMax&&windowWidth>parseInt(screenMax,10))return;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var ranges=rec.querySelectorAll('.t-range');var documentBody=document.body;if(ranges.length){Array.prototype.forEach.call(ranges,function(range){t702__triggerEvent(range,'popupOpened')})}
t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
t702__lazyLoad();t702__triggerEvent(popup,'tildamodal:show'+popupTooltipHook);t_onFuncLoad('t_forms__calculateInputsWidth',function(){t_forms__calculateInputsWidth(recId)})}
function t702_closePopup(recId){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var popupAll=document.querySelectorAll('.t-popup_show:not(.t-feed__post-popup):not(.t945__popup)');if(popupAll.length==1){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed')}else{var newPopup=[];for(var i=0;i<popupAll.length;i++){if(popupAll[i].getAttribute('data-tooltip-hook')===popupTooltipHook){popupAll[i].classList.remove('t-popup_show');newPopup.push(popupAll[i])}}
if(newPopup.length===popupAll.length){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed')}}
if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');popup.classList.remove('t-popup_show');document.body.classList.remove('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);t702__triggerEvent(popup,'tildamodal:close'+popupTooltipHook)}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{hitType:'pageview',page:virtPage,title:virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t890_init(recId,offset){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t890');if(!container)return;var windowOffset=offset||window.innerHeight;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;window.addEventListener('scroll',t_throttle(function(){if(window.pageYOffset>windowOffset){container.style.display='block'}else{t890__fadeOut(container)}},200));var isSafari=/^((?!chrome|android).)*safari/i.test(navigator.userAgent);rec.addEventListener('click',function(e){if(e.target.closest('.t890__arrow')){isSafari?t890__animateScrollPolyfill(0):t890__scrollToTop()}})}
function t890__fadeOut(el){if(el.style.display==='none')return;var opacity=1;var timer=setInterval(function(){el.style.opacity=opacity;opacity-=0.1;if(opacity<=0.1){clearInterval(timer);el.style.display='none';el.style.opacity=null}},20)}
function t890__scrollToTop(){if(window.isIE){window.scrollTo(0,0)}else{window.scrollTo({left:0,top:0,behavior:'smooth'})}}
function t890__animateScrollPolyfill(target){var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(target>bottomViewportPoint)target=bottomViewportPoint;if(target===window.pageYOffset)return!1;var currentPosition=window.pageYOffset;var step=(target-currentPosition)/30;var difference=window.pageYOffset;var timerID=setInterval(function(){difference+=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if((target-currentPosition<0&&window.pageYOffset<=target)||(target-currentPosition>0&&window.pageYOffset>=target)){clearInterval(timerID);document.body.removeAttribute('data-scrollable')}},10)}
function t602_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var indicator=rec.querySelector('.t602__indicator');if(!indicator)return;window.addEventListener('scroll',t_throttle(function(){var documentHeight=document.body.clientHeight;var windowScrollTop=document.documentElement.scrollTop;var windowHeight=window.innerHeight;var scrollPercent=(windowScrollTop/(documentHeight-windowHeight))*100;indicator.style.width=scrollPercent+'%'},100))}
function t389_scrollToTop(){var duration=700;var difference=window.pageYOffset;var step=10*difference/duration;var timer=setInterval(function(){difference-=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(window.pageYOffset===0){document.body.removeAttribute('data-scrollable');clearInterval(timer)}},10)}
window.requestAnimationFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60)}})();function t270_scroll(hash,offset){if(!hash)return;t270_checkLoad(hash,offset);var excludeHashes=['#!/tproduct/','#!/tab/','#opencart']
if(excludeHashes.includes(hash)){return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;t270_scrollToEl(hash,offset);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_checkLoad(hash,offset){if(window.t270_loadChecked)return;var sliderWrappers=document.body.querySelectorAll('.t-slds__items-wrapper');if(!sliderWrappers.length)return;var lastWrapper=sliderWrappers[sliderWrappers.length-1];var sliderImgs=lastWrapper?lastWrapper.querySelectorAll('.t-slds__bgimg'):[];var lastImg=sliderImgs[sliderImgs.length-1];var imageUrl=lastImg?window.getComputedStyle(lastImg).backgroundImage:'';imageUrl=imageUrl.substring(5,imageUrl.length-2);var preloaderImg=document.createElement('img');preloaderImg.src=imageUrl?imageUrl:'';preloaderImg.addEventListener('load',function(){t270_scroll(hash,offset);window.t270_loadChecked=!0})}
function t270_scrollToEl(hash,offset){var SCROLL_DURATION_MS=500;var body=document.body;if(body.getAttribute('data-scroll'))return;var scrollTargetY=t270_getTarget(hash,offset);if(isNaN(scrollTargetY))return;var canSmoothScroll=window.CSS&&window.CSS.supports('scroll-behavior','smooth')&&'scrollBehavior' in document.documentElement.style;var userAgent=navigator.userAgent.toLowerCase();var isAndroid=userAgent.indexOf('android')!==-1;if(window.isMobile&&!isAndroid&&canSmoothScroll){body.setAttribute('data-scroll','true');window.scrollTo({left:0,top:scrollTargetY,behavior:'smooth'});setTimeout(function(){body.removeAttribute('data-scroll')},SCROLL_DURATION_MS)}else{t270_smoothScrollTo(scrollTargetY,SCROLL_DURATION_MS)}}
function t270_smoothScrollTo(targetY,duration=500){var body=document.body;var startY=window.scrollY||window.pageYOffset;var deltaY=targetY-startY;var startTime=performance.now();function easeInOutQuad(t){return Math.pow(t,2)}
function scroll(){var currentTime=performance.now();var elapsedTime=Math.min((currentTime-startTime)/duration,1);var ease=easeInOutQuad(elapsedTime);window.scrollTo(0,startY+deltaY*ease);if(elapsedTime<1){requestAnimationFrame(scroll)}else{body.removeAttribute('data-scroll');body.removeAttribute('data-scrollable');window.scrollTo(0,targetY)}}
body.setAttribute('data-scroll','true');body.setAttribute('data-scrollable','true');requestAnimationFrame(scroll)}
function t270_getTarget(hash,offset){var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"], div[id="'+hash.substr(1)+'"]');if(!target)return}
target=parseInt((target.getBoundingClientRect().top+window.pageYOffset)-offset,10);target=Math.max(target,0);return target}